### ISSUE TITLE
Support username/password for jenkins_client_api

### ISSUE THREAD

**Issue by dkiser** [sensu-plugins/sensu-plugins-jenkins#14]
In order to support authenticated Jenkins URL's, please add username and password options to the functions below throughout the plugin.

``` ruby
  def jenkins
    @jenkins ||= JenkinsApi::Client.new(server_url: config[:url], log_level: 3)
  end
```

https://github.com/arangamani/jenkins_api_client suggest `username` and `password` args as so:

``` ruby
@client = JenkinsApi::Client.new(:server_ip => '0.0.0.0',
         :username => 'somename', :password => 'secret password')
```

**Comment by eheydrick** [comment]
This would be a nice addition. I'd take a PR adding it.

**Comment by seth-paxton** [comment]
Just submitted a PR for this if you want to use it. 

https://github.com/sensu-plugins/sensu-plugins-jenkins/pull/15

**Comment by sstarcher** [comment]
#15 should close this
