### ISSUE TITLE
New Gem?

### ISSUE THREAD

**Issue by seth-paxton** [sensu-plugins/sensu-plugins-jenkins#16]
Doesn't look like my changes created a new Gem. Any ideas what I might be missing?

http://sensu-plugins.io/docs/b_and_r.html

According to that, the version needs bumped and a we need to tag a release.

**Comment by eheydrick** [comment]
Hey @seth-paxton, thanks for asking. I will cut a new release.

**Comment by eheydrick** [comment]
[1.1.0](https://rubygems.org/gems/sensu-plugins-jenkins/versions/1.1.0) is live on rubygems. Thanks for the contribution!

**Comment by seth-paxton** [comment]
Thanks for being quick to respond! I see the updated version now.
