### ISSUE TITLE
Ruby warning

### ISSUE THREAD

**Issue by gchenuet** [sensu-plugins/sensu-plugins-jenkins#26]
Hi,

When using `check-jenkins-job-status.rb`check, i received ruby warning message about `rbreadline`:

`/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/rb-readline-0.5.3/lib/rbreadline.rb:13: warning: constant ::Fixnum is deprecated `

About the setting:
- Debian 8
- Sensu 1.0.2

Could you fix it please ?

Thanks

**Comment by majormoses** [comment]
It is not coming from the plugin code itself but rather from the gem `rb-readline` in version 0.5.3 I see the new version is 0.5.5 so we could try bumping the dependency and see if it's fixed.

**Comment by majormoses** [comment]
It looks like it is fixed looking at the code, I will PR it.

**Comment by majormoses** [comment]
@gchenuet can you verify my PR fixes it for you?
