### ISSUE TITLE
Interacting with secure Jenkins

### ISSUE THREAD

**Issue by rgeddis** [sensu-plugins/sensu-plugins-jenkins#8]
Trying to use this plugin to monitor jobs on running on a secure instance of Jenkins, however there doesn't seem to be a method to allow passing of the credentials through to the api client. Locally I have been using:

```
   def jenkins_api_client
     @jenkins_api_client ||= JenkinsApi::Client.new(
-      server_ip: config[:server_api_url],
+      server_url: config[:server_api_url],
       log_level: config[:client_log_level].to_i
     )
   end
```

Not sure if this is the best method for everybody, however I'd be happy to submit a pull request after there is feedback on the best solution.

**Comment by analytically** [comment]
Hi, yeah would love to see a PR!

**Comment by analytically** [comment]
Also, mind updating the jenkins gem to 1.4.2 and testing all scripts? https://github.com/arangamani/jenkins_api_client/blob/master/CHANGELOG.md

**Comment by rgeddis** [comment]
#9

**Comment by analytically** [comment]
Merged, thanks!
